name: Upstream Sync (PR)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/MoonTechLab/LunaTV.git || true
          git fetch upstream
          git fetch origin

      - name: Detect diff (upstream/main vs origin/main)
        id: diffcheck
        run: |
          UP=$(git rev-parse upstream/main)
          OR=$(git rev-parse origin/main || git rev-parse HEAD)
          if [ "$UP" = "$OR" ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "✅ Already up to date." >> $GITHUB_STEP_SUMMARY
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "🔄 Changes detected." >> $GITHUB_STEP_SUMMARY
          fi
          echo "- upstream: $UP" >> $GITHUB_STEP_SUMMARY
          echo "- origin  : $OR" >> $GITHUB_STEP_SUMMARY

      - name: Create sync branch from upstream
        if: steps.diffcheck.outputs.changes == 'true'
        run: |
          git checkout -B ci/upstream-main upstream/main
          git push -f origin ci/upstream-main

      - name: Open/Update PR
        id: cpr
        if: steps.diffcheck.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Sync: upstream → main"
          body: "Automated sync from MoonTechLab/LunaTV."
          branch: ci/upstream-main
          base: main

      - name: Summarize result
        run: |
          if [ "${{ steps.diffcheck.outputs.changes }}" = "true" ]; then
            echo "📌 PR: ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
          fi
