name: Upstream Sync (PR)

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write   # keep for the delete-runs step below

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream & fetch
        run: |
          # IMPORTANT: new upstream
          git remote add upstream https://github.com/MoonTechLab/LunaTV.git || true
          git fetch upstream

      # Create a branch that mirrors upstream/main exactly
      - name: Create sync branch from upstream
        run: |
          git checkout -B ci/upstream-main upstream/main
          git push -f origin ci/upstream-main

      - name: Open/Update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync: upstream → main"
          body: "Automated sync from MoonTechLab/LunaTV."
          head: ci/upstream-main
          base: main
          branch: ci/upstream-main
          commit-message: "chore(sync): upstream → main"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
